_target_: augment.synonym.ApplySynonymAug
lang_pair: ${data.lang}
lang1: fra
lang2: eng
aug_min: 1
aug_max: 10
aug_p: 0.3
stopwords: null
tokenizer: null
reverse_tokenizer: null
stopwords_regex: null
verbose: 0