_target_: utils.patience.Patience
patience: 3 # number of epochs to accept without improvement before stopping the run
mode: max # 'min' or 'max' depending on the metric (see below), if the best value is the lowest, use 'min'
metric: sacrebleu # metric to be used for early stopping, 'loss' or it must be in evaluation_metrics (see main.yaml)
