defaults:
    - _self_
    - tokenizer: character
    - model: seq2seq
    - optimizer: adamw
    - criterion: crossentropy
data:
    name: wmt14
    lang: cs-en # available 'cs-en', 'de-en', 'fr-en', 'hi-en', 'ru-en'
    dir: './data'

wandb:
    entity: crutch
    project: "Data Augmentation for Neural Machine Translation"

emb_size: 512
src_vocab_size: null
tgt_vocab_size: null

batch_size: 32
max_length: 512
lr: 0.001
epochs: 100
dropout: 0.1 # 0.1 is the default from the https://pytorch.org/tutorials/beginner/colab tutorial


name: null # if null, it will be assigned automatically as time
group: null # todo: change automatic selection of run group

seed: 42
device: null # if null auto cofiguration happens in this order based on availability: gpu, mps, cpu
